#!/bin/bash

# interval between changing wallpapers in seconds
INTERVAL=2
items=''

for arg in $@
do
    if [[ -d $arg ]]; then
        for item in $(ls $arg)
        do
            items+="$arg$item "
        done
    elif [[ -f $arg ]]; then
        items+=" $arg "
    fi
done

selection="$(shuf -n 1 -e $items)"
cp $selection ~/.config/wall.png

xwallpaper --zoom ~/.config/wall.png

if [[ ${@: -1} = "carousel" ]]; then
    sleep $INTERVAL
    $0 $@
fi
